version: '3'
services:
  build-rms:
    image: weilong12/rms-docker-img:v6
    container_name: rms-docker-container_library_management  # Correct format
    ports:
      - "8000:5500"
    networks:
      - monitoring-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus  # Correct format
    volumes:
      - /prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring-network

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter  # Correct format
    ports:
      - "9100:9100"
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana
    container_name: grafana  # Correct format
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge
