services:
 build-rms:
   build:
     context: .
     dockerfile: Dockerfile 
   image: weilong12/rms-docker-img:v5
   container_name: rms-docker-container_library_management
   ports:
     - "8000:5500"
     