apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default  # Replace with your desired namespace
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'rms-app'
        static_configs:
          - targets: ['build-rms:5500']
        metrics_path: '/metrics'

      - job_name: 'node'
        static_configs:
          - targets: ['node-exporter:9100']
        metrics_path: '/metrics'
