apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default  # Replace with your desired namespace if needed
data:
  prometheus.yml: 
    global:
      scrape_interval: 15s  # Scrape every 15 seconds

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]  # Prometheus instance

      - job_name: "jenkins"
        static_configs:
          - targets: ["jenkins:8080"]  # Jenkins container hostname
        metrics_path: "/metrics"

      - job_name: "rms-app"
        static_configs:
          - targets: ["build-rms:5500"]  # RMS app container hostname
        metrics_path: "/metrics"

      - job_name: "node"
        static_configs:
          - targets: ["node-exporter:9100"]  # Node Exporter container hostname
        metrics_path: "/metrics"
