apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090  # This is the port on which Prometheus will be accessible
      targetPort: 9090  # This is the container's internal port
  type: NodePort  # Type can be ClusterIP, NodePort, or LoadBalancer based on your needs
