---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default  # Adjust the namespace as needed
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s  # Scrape every 15 seconds

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]  # Prometheus instance

      - job_name: "jenkins"
        static_configs:
          - targets: ["jenkins:8080"]  # Jenkins container hostname
        metrics_path: "/metrics"

      - job_name: "rms-app"
        static_configs:
          - targets: ["build-rms:5500"]  # RMS app container hostname
        metrics_path: "/metrics"

      - job_name: "node"
        static_configs:
          - targets: ["node-exporter:9100"]  # Node Exporter container hostname
        metrics_path: "/metrics"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: default  # Adjust the namespace as needed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: default  # Adjust the namespace as needed
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
  type: ClusterIP  # Change to LoadBalancer if you want external access
